module.exports.addProduct = require('./addProduct.controller')
module.exports.updateProduct = require('./updateProduct.controller')
module.exports.deleteProduct = require('./deleteProduct.controller')
module.exports.getAllProducts = require('./getAllProducts.controller')
module.exports.getProductById  = require('./getProductById.controller')
