module.exports.addProduct = require('./addProduct.service')
module.exports.updateProduct = require('./updateProduct.service')
module.exports.deleteProduct = require('./deleteProduct.service')
module.exports.getAllProducts = require('./getAllProducts.service')
module.exports.getProductById  = require('./getProductById.service')
